### ISSUE TITLE
iOS模拟器运行失败，请问是否支持M1 Mac模拟器？

### ISSUE THREAD

**Issue by sunjianan9900** [RxReader/wechat_kit#124]
pod install 时候出现警告

```
wechatsdk no_pay
/Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/wechat_kit-5.0.2/ios/wechat_setup.rb:53:in `block in <main>': uninitialized constant URI (NameError)
        from /Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/wechat_kit-5.0.2/ios/wechat_setup.rb:49:in `each'
        from /Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/wechat_kit-5.0.2/ios/wechat_setup.rb:49:in `<main>'
Downloading dependencies
```

然后运行在真机上没问题，运行在M1 MAC的模拟器上显示：

```
Error (Xcode): In /Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/wechat_kit-5.0.2/ios/Libraries/OpenSDK1.9.9_NoPay/libWeChatSDK.a(WechatAuthSDK.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/wechat_kit-5.0.2/ios/Libraries/OpenSDK1.9.9_NoPay/libWeChatSDK.a' for architecture arm64

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

![image](https://user-images.githubusercontent.com/10936316/223368192-55d1e010-cb20-4d20-81d3-b7a4a2fcaba6.png)

**Comment by sunjianan9900** [comment]
https://developers.weixin.qq.com/community/develop/doc/000c6275b68bf014265b30dc256800
