### ISSUE TITLE
微信点击允许之后返回APP，APP发生闪退

### ISSUE THREAD

**Issue by ZoeyGit** [RxReader/wechat_kit#146]
E/AndroidRuntime(16826): java.lang.RuntimeException: Unable to destroy activity {com.zhikaodian.tk/com.zhikaodian.tk.wxapi.WXEntryActivity}: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
E/AndroidRuntime(16826): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6828)
E/AndroidRuntime(16826): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6874)
E/AndroidRuntime(16826): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:57)
E/AndroidRuntime(16826): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:50)
E/AndroidRuntime(16826): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
E/AndroidRuntime(16826): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
E/AndroidRuntime(16826): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3082)
E/AndroidRuntime(16826): 	at android.os.Handler.dispatchMessage(Handler.java:117)
E/AndroidRuntime(16826): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(16826): 	at android.os.Looper.loop(Looper.java:293)
E/AndroidRuntime(16826): 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
E/AndroidRuntime(16826): 	at android.app.ActivityThread.main(ActivityThread.java:9975)
E/AndroidRuntime(16826): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/AndroidRuntime(16826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
E/AndroidRuntime(16826): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
E/AndroidRuntime(16826): 	at java.util.ArrayList.remove(ArrayList.java:506)
E/AndroidRuntime(16826): 	at com.tencent.vod.flutter.tools.TXFlutterEngineHolder$1.onActivityDestroyed(TXFlutterEngineHolder.java:96)
E/AndroidRuntime(16826): 	at android.app.Application.dispatchActivityDestroyed(Application.java:549)
E/AndroidRuntime(16826): 	at android.app.Activity.dispatchActivityDestroyed(Activity.java:1601)
E/AndroidRuntime(16826): 	at android.app.Activity.onDestroy(Activity.java:2877)
E/AndroidRuntime(16826): 	at android.app.Activity.performDestroy(Activity.java:8875)
E/AndroidRuntime(16826): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1379)
E/AndroidRuntime(16826): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6815)
E/AndroidRuntime(16826): 	... 14 more

-------
Flutter 版本 3.22.2    Dart 版本  3.4.3

**Comment by ZoeyGit** [comment]
项目同时引用了&nbsp;tencent_kit   superplayer_widget  以及 flutter_tencent_captcha  其他插件就不是腾讯系列了
&nbsp;


1017415870
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月10日(星期三) 晚上10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RxReader/wechat_kit] 微信点击允许之后返回APP，APP发生闪退 (Issue #146)














 
E/AndroidRuntime(16826): at com.tencent.vod.flutter.tools.TXFlutterEngineHolder$1.onActivityDestroyed(TXFlutterEngineHolder.java:96)
 
这是腾讯 sdk 的问题，看起来是你引入的另外一个插件引发的

**Comment by ZoeyGit** [comment]
确实如此  superplayer_widget 腾讯云播放插件 导致的闪退 我注释掉运行正常

**Comment by winter-tech** [comment]
我只是升级了一些第三方库，也是闪退了，我没有superplayer_widget这个库也闪退
