### ISSUE TITLE
Platform._version crash

### ISSUE THREAD

**Issue by fee-studio** [RxReader/wechat_kit#98]
when run get qrcode image on WEB platform, will happen crash:

Error: Unsupported operation: Platform._version
    at Object.throw_ [as throw] (http://localhost:61141/zhaoxi/dart_sdk.js:5061:11)
    at Function._version (http://localhost:61141/zhaoxi/dart_sdk.js:54689:17)
    at Function.get version [as version] (http://localhost:61141/zhaoxi/dart_sdk.js:54763:27)
    at get _version (http://localhost:61141/zhaoxi/dart_sdk.js:54633:27)
    at Function.desc.get [as _version] (http://localhost:61141/zhaoxi/dart_sdk.js:5552:17)
    at Function.get version [as version] (http://localhost:61141/zhaoxi/dart_sdk.js:54607:26)
    at Object._getHttpVersion (http://localhost:61141/zhaoxi/dart_sdk.js:193006:31)
    at new _http._HttpClient.new (http://localhost:61141/zhaoxi/dart_sdk.js:188203:28)
    at Function.new (http://localhost:61141/zhaoxi/dart_sdk.js:182682:16)
    at _createResponse (http://localhost:61141/zhaoxi/packages/wechat_kit_extension/wechat_kit_extension.dart.lib.js:376:48)
    at _createResponse.next (<anonymous>)
    at runBody (http://localhost:61141/zhaoxi/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:61141/zhaoxi/dart_sdk.js:38690:7)
    at Object._createResponse (http://localhost:61141/zhaoxi/packages/wechat_kit_extension/wechat_kit_extension.dart.lib.js:374:18)
    at Function.getAccessToken (http://localhost:61141/zhaoxi/packages/wechat_kit_extension/wechat_kit_extension.dart.lib.js:66:35)
    at wechat_utils.WechatUtils.__.getQrCode (http://localhost:61141/zhaoxi/packages/zhaoxi/parse/manager/tomato_manager.dart.lib.js:3476:75)
    at getQrCode.next (<anonymous>)
    at runBody (http://localhost:61141/zhaoxi/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:61141/zhaoxi/dart_sdk.js:38690:7)
    at wechat_utils.WechatUtils.__.getQrCode (http://localhost:61141/zhaoxi/packages/zhaoxi/parse/manager/tomato_manager.dart.lib.js:3471:20)
    at me_page._MePageState.new.<anonymous> (http://localhost:61141/zhaoxi/packages/zhaoxi/pages/me/me_page.dart.lib.js:577:45)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:61141/zhaoxi/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:61141/zhaoxi/dart_sdk.js:38690:7)
    at setting_list_item.SettingListItem.new.<anonymous> (http://localhost:61141/zhaoxi/packages/zhaoxi/pages/me/me_page.dart.lib.js:576:130)
    at Object._checkAndCall (http://localhost:61141/zhaoxi/dart_sdk.js:5268:16)
    at Object.callMethod (http://localhost:61141/zhaoxi/dart_sdk.js:5311:17)
    at Object.dsend (http://localhost:61141/zhaoxi/dart_sdk.js:5314:17)
    at http://localhost:61141/zhaoxi/packages/zhaoxi/components/setting_list/setting_list_item.dart.lib.js:262:18
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:61141/zhaoxi/packages/flutter/src/material/icon_button.dart.lib.js:33828:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/recognizer.dart.lib.js:185:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/tap.dart.lib.js:393:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/tap.dart.lib.js:205:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/tap.dart.lib.js:154:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/recognizer.dart.lib.js:428:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/pointer_router.dart.lib.js:85:9)
    at http://localhost:61141/zhaoxi/packages/flutter/src/gestures/pointer_router.dart.lib.js:115:26
    at LinkedMap.new.forEach (http://localhost:61141/zhaoxi/dart_sdk.js:26433:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/pointer_router.dart.lib.js:113:29)
    at pointer_router.PointerRouter.new.route (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/pointer_router.dart.lib.js:108:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:362:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:347:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:61141/zhaoxi/packages/flutter/src/rendering/layer.dart.lib.js:5118:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:61141/zhaoxi/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:61141/zhaoxi/dart_sdk.js:179667:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:61141/zhaoxi/dart_sdk.js:160119:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:61141/zhaoxi/dart_sdk.js:160965:49)
    at http://localhost:61141/zhaoxi/dart_sdk.js:161384:28
    at http://localhost:61141/zhaoxi/dart_sdk.js:161340:16
    at loggedHandler (http://localhost:61141/zhaoxi/dart_sdk.js:161058:11)

**Comment by AlexV525** [comment]
Not related to wechat_kit.
